services:
  - type: web
    name: bpmde-terminal
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: KALSHI_API_KEY
        value: 5ce679c0-46dd-42c6-8f46-4311f8321034
      - key: KALSHI_PRIVATE_KEY
        sync: false
